ALTER TABLE matches
  ADD COLUMN odds_team1 DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  ADD COLUMN odds_team2 DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  ADD COLUMN odds_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
